import React from 'react'
import logo from "../Icon/logo.svg"

function PageTen() {
    return (
            <div id="main-container">
                <div className='position-relative'>
                <h2
                    style={{
                        backgroundColor: "rgb(211,211,211)",
                        margin: "10% 20% 10% 25%",
                        padding: "2%"
                    }}
                >
                    Job Application Submission Email Template</h2>
                <img src={logo} alt="Logo" className='position-absolute top-70 bottom-70 start-50 translate-middle-y' />

                </div>
                {/* <i class="fa fa-send blue-color"></i> */}
                <div
                    style={{
                        backgroundColor: "rgb(247, 242, 242)",
                        margin: "10% 20% 10% 25%",
                        padding: "2%",
                        borderTop: "2px solid rgb(77, 1, 77)"
                    }}
                >
                    <h5
                        style={{
                            textAlign: "center",
                            color: "rgb(109, 2, 109)",
                            paddingTop: "8%",
                            paddingBottom: "5%"
                        }}
                    >
                        <strong>Application Submitted</strong>
                    </h5>
                    <p style={{ marginLeft: "5%", marginBottom: "5%", fontSize: "20px" }}>
                        <strong>Hello Folashade,</strong><br />
                        Your Job Application has been sent to LurisByteRM. A copy of your
                        resume is attached with the email. Goodluck!
                    </p>
                    <div>
                        <p
                            style={{
                                fontSize: "15px",
                                backgroundColor: "rgb(240, 238, 252)",
                                padding: "10px 0px 25px 40px",
                                margin: "70px 0px 1px 0px"
                            }}
                        >
                            <em>Please do not reply directly to this autogenerated email</em>
                        </p>
                    </div>
                    <div
                        style={{
                            fontSize: "15px",
                            backgroundColor: "rgb(240, 238, 252)",
                            borderTop: "2px solid rgb(75, 0, 75)",
                            padding: "10px 0px 25px 100px",
                            margin: "2px 0px 30px 0px"
                        }}
                    >
                        &copy Copyright 2022. A product of ByteWorks Technology Solution
                        Limited
                    </div>
                </div>
            </div>
    )
}

export default PageTen